CREATE OR ALTER FUNCTION dbo.ufn_GetSalaryLevel(@Salary DECIMAL(18, 4))
RETURNS VARCHAR(10)
AS
BEGIN	
	IF @Salary < 30000
		RETURN 'Low'
	ELSE IF @Salary BETWEEN 30000 AND 50000
		RETURN 'Average'
	
	RETURN 'High'
END